### ISSUE TITLE
Bug with UI Scale in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#12]
If I set the scale to 100% on one toon, then switch to another the interface will say 100% is set, but the UI will still be larger.

UI should be 100%, but it's closer to 130% I think.

<img width="1966" alt="image" src="https://github.com/user-attachments/assets/15eff41a-385e-4b4c-b612-61fd2fb56513">

UI says 100%

<img width="857" alt="image" src="https://github.com/user-attachments/assets/5b94c2c0-2234-4308-b21b-aa4c2401be48">

Bump it to 140% to show issue..

<img width="854" alt="image" src="https://github.com/user-attachments/assets/b9b3e01b-81d9-4d23-ae53-39eee47a94e7">

Now back to 100%...

<img width="851" alt="image" src="https://github.com/user-attachments/assets/25bceb58-3022-44f7-aa72-bd7e3c1d317f">

And then open trade window... and RM is the right size.

<img width="1966" alt="image" src="https://github.com/user-attachments/assets/32f56401-4bf5-419e-b7da-4442eda62c4d">

But then when you log in with another toon, it's back to large again.

<img width="1966" alt="image" src="https://github.com/user-attachments/assets/a0448af5-adf4-4922-86aa-a0479c4272ba">

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

I appreciate the detailed step-by-step, but I wasn't able to reproduce the issue.

The scale of Recipe Master's main frame is determined by the effective scale of [UIParent](https://warcraft.wiki.gg/wiki/UI_scaling#UIParent) plus the value of UI Scale set in the options frame ([which translates to between 0 and 0.4](https://github.com/BrenoLudgero/Recipe_Master/blob/main/Vanilla/Source/Interface/Setup/OptionsFrameSetup.lua#L15)) in [EventHandler.lua](https://github.com/BrenoLudgero/Recipe_Master/blob/main/Vanilla/Source/Handlers/EventHandler.lua#L14).

Unfortunately, I'm not able to accurately test this behavior since your resolution is way higher than my current monitor resolution.
