### ISSUE TITLE
Characters are not presented in alphabetical order in recipes' tooltip

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#13]
Thanks for doing this!

<img width="387" alt="Pasted_Image_10_25_24__2_08 PM" src="https://github.com/user-attachments/assets/044d8c1b-6ef5-47a0-a05c-b3da20172aec">

It seems to be capped off at listing 5 toons. It'd be better if it listed all that it knew about on the account, I think. Maybe give people an option to limit to 5, but I'd love to see all the toons on there. (=

**Comment by Gogo1951** [comment]
Hmm, actually I think it's missing the current toon from the list. I'm on the Druid here, but it's not showing as missing for the Druid.

<img width="606" alt="image" src="https://github.com/user-attachments/assets/258b5ff7-c3f2-4d76-ad39-123fda0599a6">

And it'd be good if the list could be alphabetized. (=

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

I'm glad you've been enjoying the feature :)

I haven't implemented a limit to how many characters are displayed, but a character must have the profession learned in order to be in one of the lists. Could that be the case?

About the current character not being on any of the lists: this was a deliberate choice to avoid redundancy since "Already known" is displayed in red on the tooltip.

**Comment by Gogo1951** [comment]
Yeah I figured it was a design choice. I added a simple alphabetical sort in a PR.

I just came back to Classic Era about 2 months ago... just leveling new toons and enjoying myself. Messing around mostly. This feature is great for helping me collect recipes. Thanks!

**Comment by BrenoLudgero** [comment]
My pleasure! And thank you for the pull request! 

The feature will be implemented in the next update.
