### ISSUE TITLE
Learned enchantments not being recognized on languages other than English

### ISSUE THREAD

**Issue by BrenoLudgero** [BrenoLudgero/Recipe_Master#8]
Sorry, maybe it's not quite the same problem as mentioned above. In principle, it can be said that not all recipes are recognized as learned. Here is a screenshot with two examples. You can also see this from the total number of recipes learned, which is far too low for the level.
![enchanting_recipemaster](https://github.com/user-attachments/assets/2d8ce50b-9c35-4a99-96e2-958ec6da6d55)
Edit: Tested in the Classic Cataclysm.

_Originally posted by @tanrak in https://github.com/BrenoLudgero/Recipe_Master/issues/5#issuecomment-2434362435_

**Comment by BrenoLudgero** [comment]
Enchantments are handled differently during the process of identifying learned skills in Cataclysm. With that said, the handling method is working as expected on my end:

![enchanting_window](https://github.com/user-attachments/assets/fc6a4364-36a6-4f9c-bfcf-dd309f08a24d)

Could you delete the saved variables for Recipe Master to see if there are any changes?
Those are found in .../Program Files (x86)/World of Warcraft/_classic_/WTF/Account/Account#/SavedVariables/
Make sure to delete RecipeMaster.lua and RecipeMaster.lua.bak
**This will reset your Recipe Master preferences.**

**Comment by tanrak** [comment]
Hi, the problem seems to be language-dependent. I have deleted both config files (*.lua and *.lua.bak) and then started the client in german:
![Zwischenablage_10-24-2024_01](https://github.com/user-attachments/assets/0262b832-3942-46c1-9c8b-bca863869270)
Then i deleted the configs again and started the client in english language an voila;
![Zwischenablage_10-24-2024_02](https://github.com/user-attachments/assets/c0883ee8-433b-4552-b979-bb0fef80373c)
All the learned recipes are showed up.

**Comment by BrenoLudgero** [comment]
You are correct. I followed your steps and was able to reproduce the issue.

I'll fix it ASAP.

**Comment by BrenoLudgero** [comment]
I apologize for the inconvenience, it was an oversight on my part.

The problem has been fixed and the changes will be included in the next update.

Thank you for your feedback, @tanrak!
